project:
  type: website
  output-dir: docs

website:
  title: "nftuoa-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nftuoa
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lux


